#!/bin/bash

# ./molly src/test/resources/examples_ft/delivery/simplog.ded \
#    src/test/resources/examples_ft/delivery/deliv_assert.ded \
#    --EOT 4 \
#    --EFF 2 \
#    --nodes a,b,c \
#    --crashes 0 \
#    --prov-diagrams

docker run -it \
    -v $PWD:/molly:z \
    molly sbt "run-main edu.berkeley.cs.boom.molly.SyncFTChecker $*"
